### ISSUE TITLE
modify help message for choosing valid usernames

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#10]
At the moment, the following is displayed:

> Erforderlich. 30 Zeichen oder weniger. Nur alphanumerische Zeichen (Buchstaben, Ziffern und @/./+/-/_) sind erlaubt.

Non-geeky german users do not get that äöüß do not fall under the category 'alphanumerische Zeichen'. I would really like to clarify that. But how can I modify this help text?

**Comment by mhecker** [comment]
closed by db127cec999c7105e9fee6c5e0613dfb154b168f
