### ISSUE TITLE
allow user to re-enter a story which they have left

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#11]
If a user has left a story, they can re-enter it without invitation, just by pressing a button.

**Comment by nomeata** [comment]
This would „leaving a story“ turn into an „auto-skip“ that can be disabled and enabled, wouldn’t it?

**Comment by mohrm** [comment]
Yes, but why not have such a function? If the story runs long, and I don't have time right now, why not join later again?

**Comment by mohrm** [comment]
This issue is _not_ closed. If I leave a story, it is not displayed anymore. So, unless I have remembered its id and manually visit the story's page, I cannot effectively re-join the story.
Stories which I have left have to be displayed on the overview page.

**Comment by nomeata** [comment]
I don’t think there is a reason to hide them, now that leaving is just skip-always. Fixing that.
