### ISSUE TITLE
display commit id of last build on start page

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#28]
Now that travis automatically deploys on openshift, I do not know anymore which commit is live...

**Comment by qznc** [comment]
Fixed as of revision 05b9e15

**Comment by qznc** [comment]
Oops, I broke it for OpenShift.

**Comment by qznc** [comment]
Reverted and it works again. @mohrm you should look at the error logs. I cannot debug OpenShift.

**Comment by mohrm** [comment]
it works :+1:

**Comment by nomeata** [comment]
Wouldn't it make more sense to read the commit once on start? Otherwise you read the file often, and show the wrong commit when the repo is upgraded, but the server not restarted.

**Comment by mohrm** [comment]
@nomeata probably...
Is the settings.py only read once on startup? Then I could put the code in there.

**Comment by qznc** [comment]
Imho it does read it once.

**Comment by nomeata** [comment]
May have misread the code, sorry.

**Comment by nomeata** [comment]
Ok, you are right. Sorry for the noise.
