### ISSUE TITLE
publishing finished stories should be explicit

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#3]
At the moment, every user can see the finished story. This may not be what the participating users want. So, the suggestion is to keep the finished story unpublished until explicit action is taken.

Ideas:
- startUser can publish
- someone can express desire to publish and story is published if everyone/the majority agrees
- anyone can publish

**Comment by lohner** [comment]
Pull Request #19 addresses this by following your first suggestion: startUser can publish the story.
