### ISSUE TITLE
there should be an explanation of the symbols

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#31]
In particular the mobile users cannot see the tooltip and therefore do not get any information about the meaning of the symbols. Partly the symbols are not very self-explanatory (what is the connection between sunglasses and publishing?), so let's add some short explanations.

**Comment by ratefuchs** [comment]
Now the buttons should be removed from the main page and moved into the respective story pages, and have textual descriptions.

**Comment by mohrm** [comment]
So, now there are no symbols anymore, right? Then this issue could be closed...

**Comment by nomeata** [comment]
Only if you agree with my UI changes of course...
