### ISSUE TITLE
moar tests

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#32]
We have a pleathora of new features now but most of the new features are untested. So we need to add more tests. A code coverage tool could help to uncover untested code.

**Comment by qznc** [comment]
Surprise, views.py has bad coverage: 23%

**Comment by mohrm** [comment]
On 02.06.2016 16:59, Andreas Zwinkau wrote:

> Surprise, views.py has bad coverage: 23%

I am surprised, that views.py has a non-zero coverage. Presently, the
tests only test models.py...

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mohrm/umklapp_site/issues/32#issuecomment-223318573, or
> mute the thread
> https://github.com/notifications/unsubscribe/ABIiGbAv2r5HYwD2Wfk-2gf-WIiRLVRVks5qHu_KgaJpZM4IskuQ.

## 

Karlsruher Institut für Technologie (KIT) IPD Snelting

Martin Mohr
wissenschaftlicher Mitarbeiter

Am Fasanengarten 5, Gebäude 50.34, Raum 022
76131 Karlsruhe

Telefon: +49 721 608-48352
E-Mail: martin.mohr@kit.edu

http://pp.ipd.kit.edu

KIT - Universität des Landes Baden-Württemberg und
nationales Großforschungszentrum in der Helmholtz-Gemeinschaft

**Comment by qznc** [comment]
Travis now fails if total coverage falls under 75%. The limit can be gradually raised. The plan:
1. Run `make test-coverage`
2. Look at `htmlcov/index.html` to find uncovered code
3. Write moar tests
4. Repeat

**Comment by nomeata** [comment]
Code coverage now at 94%. I am unable to write test cases but very long sequences of interactions and expected behaviour. Are these what people call Akzeptanztests?

**Comment by qznc** [comment]
As of rev 8c3e774, travis checks for 92% coverage and we are at 94%. This leaves a little space to quickly push some code.

We will never reach 100%. For example, you cannot test the OpenShift stuff.

I think this issue can be closed.
