### ISSUE TITLE
Using the browser's back button doesn't work as expected if overview was open for more then 20 seconds.

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#33]
Imagine the following scenario:
1. Open '/' (overview)
2. Wait for half a minute
3. Click on one of the finished stories
4. After reading click the browser's back button

After step 4. one would expect to see the same site as just before step 3.
Instead one gets just the content of the `<div id="content">` without any style sheet information or other surrounding data.

I guess this issue stems from the fact, that the call to `jQuery.get` in `startRefresh` uses the same url as the overview site itself. However when requested via ajax only the `<div>` container is transferred. Therefore confusing the browsers cache of the site.

**Comment by mohrm** [comment]
sounds like the kind of fun I'd rather not like to have...

**Comment by qznc** [comment]
It also works to "view source" (with Chrome) instead of using the back button.

**Comment by nomeata** [comment]
Maybe some option to jQuery fixes that? Or just add an unused query parameter to the URL.
