### ISSUE TITLE
The action column for finished stories should not be visible if I can't take any action on any finished story.

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#34]

**Comment by nomeata** [comment]
What about leaving, that is always possible.

**Comment by mohrm** [comment]
yes, but if all stories started by me are running, then I can't do anything with the finished stories I can see....ah I think, the real problem here is that there are two ways of showing stories:
- via link if I participated
- via icon if I am external and the story is published
  there should be only one way. Then, I always would have one possible action.

**Comment by nomeata** [comment]
Still confused. Are we talking about the running stories, or the finished stories?

**Comment by mohrm** [comment]
finished.

**Comment by nomeata** [comment]
Ah, then it is fixed now by #6954a11
