### ISSUE TITLE
there should be a "back" button on the story detail page

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#39]
If I click on an unfinished story, I see a text indicating whose turn it is and a button / link labeled "Geschichte verlassen". Since it's not my turn and this is the only thing I can do, I may think that this button / link just brings me back to the overview page and does not do anything else (like "diese Seite verlassen"). We should add a " back" button / link, so that it is made clear that "Geschichte verlassen" is something different.

**Comment by mohrm** [comment]
Note: I do not insist on a button. I want a colored area with a label, which I can click on and which then leads me to another page.

**Comment by nomeata** [comment]
Confirm this issue. I tried to  hange the button label, but could not think of anything better yet.

**Comment by nomeata** [comment]
The button is now labeled differently. Is this sufficient, or is it still be non-obvious how to return to the overview?

**Comment by mohrm** [comment]
I think it is clear now, thx!
