### ISSUE TITLE
Vote to skip

### ISSUE THREAD

**Issue by qznc** [mohrm/umklapp_site#43]
If a single teller delays a story, the others should be able to vote.

Implementation on branch `skipvote`, but it resulted in "Internal Server Error". Needs error log powers of @mohrm

**Comment by mohrm** [comment]
I just applied your commit and it appears to run just fine. I cannot see anything suspicious in the runtime logs and can vote for skip. There were some errors during deployment, but I think they do not have anything to do with running the application (pip did not find the version 4.1 of 'coverage').

@qznc Can you elaborate more on the circumstances under which you observed the error?

**Comment by mohrm** [comment]
I also made an experiment:
- started a story with three users
- successful vote for skip twice
  No internal server error. 
  (btw. do we have a test case like this? :-))
  @qznc I think your feature just works. The internal server error you observed must have come from something else (i.e. it was coincidental).

**Comment by qznc** [comment]
I saw it deploy fine via Travis. Then I only got "internal server error" from rhcloud. Weird.

Anyways. It seems to work.

**Comment by nomeata** [comment]
Isn't a whole voting system not too complicated for this purpose? Why not a simple timeout? Or give the story starter dictatorship rights.

**Comment by ratefuchs** [comment]
I'd also like to see a timeout system, maybe make the timeout somehow selectable by the creator (including no timeout). Maybe we can run it parallel to this vote system.

**Comment by mohrm** [comment]
timeout was suggested in issue #9 
maybe we can discuss details there
