### ISSUE TITLE
Is leaving just "skip me always"

### ISSUE THREAD

**Issue by nomeata** [mohrm/umklapp_site#44]
We have  „Mich einmal überspringen“ and „Nicht mehr mitschreiben“. Semantically, the latter is just „Skip me always“, isn’t it? Maybe we should name it this way, for a simpler UI model.

**Comment by mohrm** [comment]
True. We should call it "skip me always"

**Comment by ratefuchs** [comment]
Is this action reversible? If not, "skip me always" might be not that good of a choice since it does not sound that definite (it does not sound as irreversibile as the current "nicht mehr mitschreiben").

**Comment by nomeata** [comment]
It should be reversible (#11), and there is no reason not to do it.

**Comment by mohrm** [comment]
we could call it "vorerst nicht mehr mitschreiben"
this would sound as reversible as it is

**Comment by mohrm** [comment]
I think this can be closed. Right?

**Comment by nomeata** [comment]
@qznc: Is it deliberate that the action is only visible if it’s _not_ your turn? I assume not.. wil fix.

Done in a773f97.

**Comment by qznc** [comment]
I did not consider it necessary to show this button, if it is your turn. I'm fine with a773f97, though.

**Comment by nomeata** [comment]
I think it’s necessary; usually only when it’s your turn you are reminded that you lost interest in this particular story :-)
