### ISSUE TITLE
Password reset sends no mail.

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#45]
When clicking "Passwort vergessen?" and requesting the password reset instructions it says you get an email. However, it seems the mail never gets sent.

**Comment by mohrm** [comment]
Yes, I did not configure E-Mailing.

**Comment by lohner** [comment]
OK.  So I'm unable to use umklapp-spielchen.rhcloud.com from @home atm. :-(

**Comment by qznc** [comment]
No problem, we can vote to skip you now. :smiling_imp:

**Comment by mohrm** [comment]
@lohner until I have configured the E-Mail-Ability, is it okay if I just change your password and send it to you via mail?

**Comment by mohrm** [comment]
@lohner you can reset your password now!

**Comment by lohner** [comment]
Thanks!
