### ISSUE TITLE
visualization of contributors

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#46]
At the moment, you can see the (other) contributors to a story if you hover over a story part with your mouse. This is bad for mobile users.

Why not show the contributors to the left of a story in a timeline-like fashion?

**Comment by nomeata** [comment]
Or, less prominent, at the end of the paragraph, in less prominent markup, like a signature?

**Comment by mohrm** [comment]
also very nice :)

**Comment by nomeata** [comment]
Thanks
