### ISSUE TITLE
Highlight unread finished stories

### ISSUE THREAD

**Issue by ratefuchs** [mohrm/umklapp_site#49]
It might be a nice feature if finished stories that a user has not read yet are highlighted. This would help in identifying newly finished stories if the finished story list gets too long.

**Comment by mohrm** [comment]
Definitely.

**Comment by qznc** [comment]
Finished stories are added to the top, so it will be only the top _k_ stories that are highlighted. You actually only need a signal that there _are_ unread finished stories.

An alternative would be to show messages (the green boxes at the top).

**Comment by qznc** [comment]
Correction: It is not necessarily the top _k_ stories. If a story is "published" much later than it is "finished" it might show up lower.

**Comment by nomeata** [comment]
I’d vote for a simple :new: symbol or something next to the title, that goes away when the user clicks on it the first time. We should, however, add a registered-on-date field to the user object, and not show stories as new that were already there when the user first registered.

**Comment by lohner** [comment]
Done in 7bd99057267b999ff92eb3b59751f32647637ccf.

**Comment by lohner** [comment]
The suggestion of @nomeata rendering those stories read that were already there when the user registered is not yet implemented. However I'd rather vote for a button "alle als gelesen markieren" as it is the users choice then whether he wants them to be marked read.
