### ISSUE TITLE
Add an optional field for an explanation of (additional) rules when starting a story 

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#50]
I think it'd be cool if one could add additional rules while creating a story. What I have in mind is just an additional textbox that is visible to all contributors of the story. What do you think?

**Comment by ratefuchs** [comment]
I fully agree. It is way better than having it in the title.

**Comment by mohrm** [comment]
Sounds good to me. There definitely seems to be a desire for additional rules.

**Comment by nomeata** [comment]
And simple to implement, as no logic is involved :-)

**Comment by ratefuchs** [comment]
I commited a first version for this issue. Rules are currently not presented in the overview, and some minor adjustments might  be needed, so I will leave this open for now.

**Comment by nomeata** [comment]
> Rules are currently not presented in the overview,

I doubt they should.

**Comment by nomeata** [comment]
Looks good. No need to keep an ticket open for things that we do not know yet. The styling on the story page could be improved, but that can just be done if someone has a good idea.
