### ISSUE TITLE
enforce encryption

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#52]

**Comment by nomeata** [comment]
With 88f7f975c17dc5146be656e6604138504ede85e2 it one can still reach the app using http, but  
http://umklapp-spielchen.rhcloud.com/static/folded.png gets redirected to https://static/folded.png, keeping the page loading when used with http. I’m reverting this commit for now.

**Comment by nomeata** [comment]
With `88f7f97` reverted it now redirects http://umklapp-spielchen.rhcloud.com/static/folded.png  to https://umklapp-spielchen.rhcloud.com/static/folded.png. It still need to be fixed for wsgi itself.

**Comment by mohrm** [comment]
did manual changes to the .htaccess directly on server
simple app restart should suffice

**Comment by mohrm** [comment]
deployment issue - has nothing to do with the app itself
