### ISSUE TITLE
Highlight finished stories where user has participated

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#54]
I think it would be nice to directly see in which of the finished stories I have participated. Therefore highlighting those or even splitting the list of finished stories into separate categories "Meine beendete Geschichten" and "Andere beendete Geschichten" would help to bring more structure into the list.

**Comment by qznc** [comment]
I would like to dig a little deeper before jumping to solutions. Why do you want this additional structure?

**Comment by lohner** [comment]
First of all, because there are different actions that can be taken on those stories that I created/participated and those of others - namely making the story public.

**Comment by qznc** [comment]
You can easily identify stories to make public by the lock symbol since 923c563.

Solved?

**Comment by lohner** [comment]
Yeah, that's ok now. Thanks!
