### ISSUE TITLE
Show which finished stories are publicly available

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#55]
Currently only the story creator can see which of the stories he started are publicly available (and he can only see that, if he is reading the story). It would be nice, if everybody who participated can see, if his/her story is publicly available.

**Comment by qznc** [comment]
I guess you are talking about the overview? Or only on the reading page?

**Comment by lohner** [comment]
Yes, I'm talking about the overview.

**Comment by qznc** [comment]
Maybe an icon after the title like "Yoda kauft eine Banane 🌐"?

**Comment by mohrm** [comment]
I like this idea. I also often asked myself whether the stories were public or not.

**Comment by ratefuchs** [comment]
Fixed in f99e96a.
I put a symbol in front of a story to indicate whether the story is public (globe) or private (lock). I put it in front so that it renders even if the title is long.

**Comment by nomeata** [comment]
>  put it in front so that it renders even if the title is long.

Why not a column on the right?

**Comment by ratefuchs** [comment]
> Why not a column on the right?

Not much thought, to be honest. I just wanted it to be there... Feel free to change the current format.

**Comment by qznc** [comment]
> Why not a column on the right?

A column is good, if you want to compare numbers quickly. For this symbol it is not necessary.

Having it close to the title makes it easier to check individually, since you don't have to find the correct row on the right.

**Comment by nomeata** [comment]
I find this imformation to be not as important that it should be before the title. It should be an unlabeled column to the right, left of the existing ones. Will fix that; revert if you don’t like it.

**Comment by nomeata** [comment]
Also, in order to reduce clutter one could consider having only icons for the private or for the public ones.
