### ISSUE TITLE
logout button covers too much area

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#56]
I think the clickable area of the logout button should cover only the text "Abmelden" plus a bit of margin. At the moment the button reaches too far to the left and right such that the whole button is around 3 times the size it should be.

See the mousepointer in this screenshot:

![abmelden](https://cloud.githubusercontent.com/assets/1277734/15816803/084ee710-2bd5-11e6-86da-32e517fa431f.png)

**Comment by qznc** [comment]
The question is, why is it not drawn as a button?

**Comment by nomeata** [comment]
I doubt there was put much thought into this; this was just a quick hack. Feel free to fix it.

**Comment by mohrm** [comment]
I also would like to have it on the top.
