### ISSUE TITLE
make user confirm input

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#58]
After a teller entered his part, show him what he has written and ask him to confirm or edit again. This way, we would have much less incomplete story parts...

**Comment by lohner** [comment]
No!! Instead, don't let the user input something that cannot be processed. I don't want to click twice everytime.

**Comment by mohrm** [comment]
You don't understand what I mean. It happens to me nearly all the time that I prematurely press some weird key combination which submits my unfinished sentence. I just want to be able to go back and correct my input.

**Comment by qznc** [comment]
The user might (accidentally) ignore the confirmation.

Alternatively, give the user 10 seconds for "undo". More complicated to implement, though.

**Comment by ratefuchs** [comment]
Maybe require the user hit the "Geschichte weiterführen"-Button and not accept an "Enter"-press and the like as submitting? I don't know whether this is possible, though. Confirmations for regular events are too annoying (the only place where I currently would accept confirmation messages is when finishing stories).

**Comment by lohner** [comment]
Implemented @ratefuchs proposal in 32c8e6c5adfc6408fa75c1c2db68d59ce84234b7.
Is this issue closed now? Or do we need an additional "undo"-option as proposed by @qznc.

**Comment by mohrm** [comment]
I think it's fine for now, thx!
