### ISSUE TITLE
allow user to leave story

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#6]
this may mean that the story has to be finished if there would be only one participant left

**Comment by mohrm** [comment]
implemented the following
- any participant of a story can leave it, as long as the remaining number of tellers is at least two
- i.e. there is not automatic finishing of stories
  If the leaving teller would leave only one behind, the action is simply not executed. In particular, no message is displayed. @nomeata, do you know how such a message display could be implemented? Via custom form? Or is there something else?

**Comment by nomeata** [comment]
How about you conflate finishing and leaving: If you are done, you quit. The rest play until all but two finish. This way, nobody can finish a story too early if others want to carry on. Maybe display that others have quit already.

Am 31. Mai 2016 22:30:46 MESZ, schrieb Martin Mohr notifications@github.com:

**Comment by mohrm** [comment]
Nice suggestion :+1: 
However, this would mean that everybody up to the last two would have to quit before anyone can see the story...sounds like we need a good notification mechanism

**Comment by nomeata** [comment]
> However, this would mean that everybody up to the last two would have to quit before anyone can see the story..

Right, but I think that’s a feature. If three or more feel like the the story can go on, then it probably should.

**Comment by mohrm** [comment]
I'll close this one because stories can be left now. Will make a new issue for the idea that popped up
