### ISSUE TITLE
what happened to source and issues links?

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#62]
At least on a small (mobile) screen I do not see them anymore. Was that intentional?

**Comment by nomeata** [comment]
Yes, intentional, but if you’d prefer it back, feel free to remove the `hidden-xs` class.

**Comment by ratefuchs** [comment]
If we introduce an "about" page someday explaining how umklapp works that would be a good place.

**Comment by mohrm** [comment]
Sounds good.
