### ISSUE TITLE
user list expands in the wrong direction

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#64]
For example, on Firefox 46 in Windows, if the browser window is maximized, the user selection list on story creation expands to the top. We now have a bunch of users, which means that you cannot see the 'select all'/'select none' links.

**Comment by lohner** [comment]
Unfortunately positioning the selection list is [not so trivial](http://pbauerochse.github.io/searchable-option-list/examples.html#proper-positioning-of-the-option-popup). However in 805a5a12f1a85e129540ab1ea4af72f98ea6369d I restricted the maximum height such that the selection box becomes scrollable if there are more then around 10 users.

Feel free to reopen this issue, if you really want the selection to expand to the bottom.
