### ISSUE TITLE
Remove highscore of most blocking users

### ISSUE THREAD

**Issue by lohner** [mohrm/umklapp_site#68]
With autoskip this list is more or less a random list of users, isn't it?

**Comment by nomeata** [comment]
Agreed

**Comment by ratefuchs** [comment]
It still collects users taking more time (if you constantly use your allocated timeout, you are more likely to end up there), but its use (ensure that users do not block stories) is now very limited. Since that was the most important reason we put it there, I'd vote for remove.

**Comment by mohrm** [comment]
yes, why not?
