### ISSUE TITLE
skip after timeout

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#9]

**Comment by qznc** [comment]
Nobody except me seems to use the "vote to skip" button. This timeout idea might be better.

**Comment by ratefuchs** [comment]
I used the "vote to skip" button a few times... but it is difficult to use "right" because there is no way of knowing how long it is the current teller's turn (except for remembering for every story when the current teller got his turn). If you have many stories open, you have a hard time estimating when it is appropriate to vote to skip somebody.

**Comment by mohrm** [comment]
So let's try this out:
- Story creator can fix a timeout.
- If a teller has not responded until the timeout hits, they get skipped.
- Nobody should continue their own last part, so something sensible should happen if this situation occurs, e.g. the story should be terminated or the teller should be skipped as well
  As a first step, we should have timestamps for the story parts. @nomeata You talked about implementing this, did you?

**Comment by nomeata** [comment]
> Story creator can fix a timeout.

Too complicated, I’d say. Just fix it to something sensible (one day)

> e.g. the story should be terminated or the teller should be skipped as well 

Definitely the latter.

>  @nomeata You talked about implementing this, did you?

No. The backwards-compatibility is putting me off :-)

**Comment by lohner** [comment]
Implementing this could be a bit tricky as design decisions have to be made: do you want a server side process that does the skipping or should every request check whether there is someone (one or even more) to skip due to a (or multiple) past timeouts?

**Comment by lohner** [comment]
Another way to implement the timeout would be to change the data model of the story:
Instead of remembering whose turn it is, the timestamp of the last action could be stored. Then `Story.whose_turn` could actually compute whose turn it is taking timeouts into account.

**Comment by mohrm** [comment]
Good idea, @lohner!

This would ease the migration because we would not need every story part to have a timestamp, right?

**Comment by qznc** [comment]
A few days @nomeata told me a few counter arguments. For example, "skip once" is not an update anymore, but you have to store them all with timestamps.

**Comment by mohrm** [comment]
I don't get it. Why not just update the timestamp if someone quits?

**Comment by mohrm** [comment]
Maybe I also don't get @lohner's suggestion...I imagine that we just associate the timestamp of the last action with each story but still remember whose turn it is. Then, if the last action was more than foo hours ago, we automatically skip the current teller. Skipping someone would count as action, so we update the last action timestamp then, of course.

**Comment by nomeata** [comment]
> I imagine that we just associate the timestamp of the last action with each story

Precisely what I’d do.

**Comment by ratefuchs** [comment]
I started story 102 (Timeout-Test) as a test for the timeout system with a test account as second contributor. I did not respond with the test account. Since I started the story more than a day ago, I expected that autoskip would be executed, but it was not.
Is this because there are only two contributors, or because it is the part following the initial sentence? Or is autoskip not working in general?

**Comment by mohrm** [comment]
Last action was set (I think) properly (yesterday approx. 8:30 am). So there are three possibilities:
- something wrong with the "apply timeouts" command
- something wrong with the cron job
- timeout is not applied due to some corner case
  I'll try to figure out what is going on there...

**Comment by mohrm** [comment]
the cron job did indeed fire, but crashed:

```
==> app-root/logs/cron_hourly.log <==
  File "umklapp/management/commands/autoskip.py", line 17, in handle
    if s.try_autoskip():
  File "umklapp/models.py", line 196, in try_autoskip
    self.advance_teller()
  File "umklapp/models.py", line 124, in advance_teller
    if not self.waiting_for().is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
```

I don't fully get what's happening there...If I understand correctly, self.waiting_for() can only return None, if self.waiting_for_teller() returns None and that can only be the case if the story is finished. The story is _not_ finished as far as I can tell, so I think I do not understand this correctly.

**Comment by lohner** [comment]
I think autoskip calls try_autoskip also on finished stories. There is no check that the story should be running. And `last_action` doesn't get updated after the story is finished.

**Comment by ratefuchs** [comment]
yes, @lohner seems to be right, there is no check that the story is still running

**Comment by mohrm** [comment]
right!
I just figured, that Simon's story is not the problem...
I'll fix it

**Comment by ratefuchs** [comment]
Now it is my turn for that story, skip seems to have happened successfully

**Comment by mohrm** [comment]
I would not be that sure...I also did some admin-magic there...
Also, the fix is not even active yet...

**Comment by mohrm** [comment]
now it still crashes but due to another problem: We seem to have stories with non-ascii characters in the title, which made the logger crash....

**Comment by mohrm** [comment]
now, the autoskip command works at least manually (6 stories were auto-skipped). Also, if I execute it twice (within a couple of seconds), it does not autoskip any story in the second run.
